### ISSUE TITLE
is this free?

### ISSUE THREAD

**Issue by monalisa62003** [areebmajeed/PHP-Login-Script#1]
Im so confused, this script is incredible and it actually works with no faults. I haven't been asked for any payments so can you reassure its for free? It makes me so happy to find it

**Comment by areebmajeed** [comment]
I am glad to know that it's working for you. The script is opensource and free, you can even contribute to the codebase.

**Comment by monalisa62003** [comment]
Thanks so much, the only thing that doesn't work is the profile, it brings up server not found even though i have it enabled
