### ISSUE TITLE
Logout after every refresh

### ISSUE THREAD

**Issue by monalisa62003** [areebmajeed/PHP-Login-Script#2]
It seems ok on a computer but on my tablet it will log me out everytime i go off. Any idea how to fix?

**Comment by monalisa62003** [comment]
Hello, i thought id just use issues here instead of creating a new one. I have implented this on my own website. Im still struggling with the show profile, it keeps giving an error. Ive tried changing things and gone back to your code but nothings worked

**Comment by areebmajeed** [comment]
Make sure that the COOKIE_DOMAIN in config.php is set correctly. For example, if your domain is "example.com", it should be set to ".example.com".

Also, I am no longer developing the script, so you might have to fix the profile issue a different way :(

**Comment by monalisa62003** [comment]
Did it ever work or am i doing something wrong

**Comment by areebmajeed** [comment]
The issue with profiles is most likely a bug.

**Comment by monalisa62003** [comment]
I looked up the error and some people think it con needs replaced with this, i really like the script but not sure its worth the time

**Comment by monalisa62003** [comment]
so i re-did the installation, and its still coming up as error:(

**Comment by monalisa62003** [comment]
would it be possible to remove the whole profile bit and use fetch in a similar way?

**Comment by monalisa62003** [comment]
Ive fixed profile issues :) well apart from logout still showing 
Does the key have to be the same one that came with the files after installing?

**Comment by areebmajeed** [comment]
> Ive fixed profile issues :) well apart from logout still showing
> Does the key have to be the same one that came with the files after installing?

What do you mean by 'key'?

**Comment by monalisa62003** [comment]
The secret key in the cookies

**Comment by areebmajeed** [comment]
You can change it, it is used to reset all the remember_me cookies and log the users out.

**Comment by monalisa62003** [comment]
Thanks i think its working now:)
